### PR TITLE
Renamed template files

### PR DESCRIPTION
**Pull request by PlrEx**
Renamed _razorpay.html.erb  to _razorpay_gateway.html.erb

### CODE REVIEW

**Comment by neerajkumar** [comment]
Your changes are breaking the application. 

Screenshot 2021-07-24 at 9 41 54 PM


I am using it in https://github.com/solidusio/solidus-demo. 

Which application are you using?

**Comment by PlrEx** [comment]
I think following from solidus-demo repo works without any error. Not sure which is the right way do it or which template naming convention is old.

**Comment by neerajkumar** [comment]
OK. I fixed your issue and release a new version `1.1.0`. Just try with this version now. Hopefully, everything will work now. 
Thanks for your testing.

**Comment by neerajkumar** [comment]
Closing the PR as its incorrect fix. The fix is here https://github.com/neerajkumar/solidus-razorpay/commit/efd806de208c50fe81a6eb1d97987642a733e78f#diff-b185513b025c2fff399ec248c09cf7520a6547eb8c6c4a78af5d5b48166fc119R26.

**Pull request closed without merging**
